#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

export DEBIAN_FRONTEND=noninteractive

deb() {
  local CMD="$1"; shift
  local URL="$1"; shift
  if ! hash "$CMD" 2>/dev/null; then
    local TMP
    TMP="$(mktemp)"
    curl -fLo "$TMP" "$URL"
    sudo dpkg -i "$TMP"
    rm "$TMP"
  fi
}

xargs sudo apt-get install -qqy <package-list
# Can't figure out the snap(1) commandline
while read -r snap; do
  sudo snap install "$snap"
done <snap-list
sudo snap refresh

sudo -H pip3 install -q neovim-remote

deb fd https://github.com/sharkdp/fd/releases/download/v7.4.0/fd-musl_7.4.0_amd64.deb
deb rg https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
deb bat https://github.com/sharkdp/bat/releases/download/v0.15.4/bat_0.15.4_amd64.deb
deb delta https://github.com/dandavison/delta/releases/download/0.1.1/git-delta_0.1.1_amd64.deb

if ! hash docker 2>/dev/null; then
  curl -fsSL get.docker.com | sudo sh
fi
sudo systemctl restart docker

if ! hash cargo 2>/dev/null; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

for config in config/*; do
  target=$(readlink -f "$config")
  if [ -d "$target" ]; then
    ln -sf "$target" -t "${XDG_CONFIG_HOME:-$HOME/.config}"
  else
    ln -sf "$target" "$HOME/.$(basename "$config")"
  fi
done

dconf load / <dconf.conf
gsettings set org.mate.mate-menu hot-key ''
gsettings set com.solus-project.brisk-menu hot-key ''

mkdir -p ~/bin
for bin in bin/*; do
  ln -sf "$(readlink -f "$bin")" "$HOME/bin/$(basename "$bin")"
done
ln -sf "$(readlink -f up)" ~/bin/up

PLUG="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim"
if [ ! -f "$PLUG" ]; then
  curl -fLo "$PLUG" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim -es -c :PlugInstall -c qa
fi

sudo usermod -a -G video,docker "$USER"
