#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

export DEBIAN_FRONTEND=noninteractive

TMP="$(mktemp)"
trap 'rm -rf -- "$TMP"' EXIT

sudo apt-get update -qqy
xargs sudo apt-get install -qqy <package-list
sudo apt-get upgrade -qqy

xargs -L1 sudo snap install <snap-list
sudo snap refresh

sudo -H pip3 install -q neovim-remote

while read -r url; do
  curl -fsSLo "$TMP" "$url"
  sudo dpkg -Ei "$TMP"
done <deb-list

if ! hash docker 2>/dev/null; then
  curl -fsSL get.docker.com | sudo sh
fi
sudo systemctl restart docker

if ! hash cargo 2>/dev/null; then
  curl --proto '=https' --tlsv1.2 -fsSfL https://sh.rustup.rs | sh
fi

for config in config/*; do
  target=$(readlink -f "$config")
  if [ -d "$target" ]; then
    ln -sf "$target" -t "${XDG_CONFIG_HOME:-$HOME/.config}"
  else
    ln -sf "$target" "$HOME/.$(basename "$config")"
  fi
done

dconf load / <dconf.conf
gsettings set org.mate.mate-menu hot-key ''
gsettings set com.solus-project.brisk-menu hot-key ''

mkdir -p ~/bin
for bin in bin/*; do
  ln -sf "$(readlink -f "$bin")" "$HOME/bin/$(basename "$bin")"
done
ln -sf "$(readlink -f up)" ~/bin/up

PLUG="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim"
if [ ! -f "$PLUG" ]; then
  curl -fsSLo "$PLUG" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim -es -c :PlugInstall -c qa
fi

sudo usermod -a -G video,docker "$USER"
