#!/bin/bash

set -e

INIT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
export DEBIAN_FRONTEND=noninteractive

link() {
  local TARGET="$1"; shift
  local LINK_NAME="$1"; shift
  mkdir -p "$(dirname "$LINK_NAME")"
  ln -sf "$INIT_DIR/$TARGET" "$LINK_NAME"
}

deb() {
  local CMD="$1"; shift
  local URL="$1"; shift
  if ! command -v "$CMD" >/dev/null; then
    local TMP
    TMP="$(mktemp)"
    curl -fLo "$TMP" "$URL"
    sudo dpkg -i "$TMP"
    rm "$TMP"
  fi
}

xargs sudo apt-get install -y <"$INIT_DIR/package-list"

mkdir -p ~/bin

deb fd https://github.com/sharkdp/fd/releases/download/v7.4.0/fd-musl_7.4.0_amd64.deb
deb rg https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
deb bat https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb

if ! command -v docker >/dev/null; then
  curl -fsSL get.docker.com | sudo sh
fi
sudo systemctl restart docker

if ! command -v cargo >/dev/null; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

link dots/bash_aliases ~/.bash_aliases
link dots/gdbinit ~/.gdbinit
link dots/gitconfig ~/.gitconfig
link dots/tmux.conf ~/.tmux.conf
link dots/vimrc ~/.vimrc
link dots/vimrc ~/.config/nvim/init.vim

dconf load / <"$INIT_DIR/dots/dconf.conf"

for b in "$INIT_DIR"/bin/*; do
  b=$(basename "$b")
  link bin/"$b" ~/bin/"$b"
done

link up ~/bin/up

if [ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  nvim -es -c :PlugInstall -c qa
fi

sudo usermod -a -G video "$USER"
